Pin TrajectPlus to 1.1.x
A recent bump to TrajectPlus 1.2.0 is causing errors when transforming data:

```
[ERROR] Error loading configuration file config/mods_config.rb:11
NoMethodError:undefined method `extended' for #<Traject::Indexer:0x0000564b796c1bd0>
Did you mean? extend
/usr/local/bundle/gems/traject-3.2.0/lib/traject/indexer.rb:231:in `rescue in block in load_config_file': ...
```

Once https://github.com/sul-dlss/traject_plus/issues/33 is closed, we can revert
this PR and/or update TrajectPlus again.